### PR TITLE
Add visits column to typed history, and sort by it

### PR DESCRIPTION
**Pull request by FrozenPigs**
This will add a visits column to new databases, as well as ones that already exists. It's incremented on each visit to the url, and it is used to sort the history so the things you visit often come first.

### CODE REVIEW

**Comment by jmercouris** [comment]
This is a very useful patch. It makes a lot of sense, so you get a fuzzy match that also considers frequency! Thank you for your submission! We'll try to get this tested and merged ASAP (we are making a lot of changes on branches and there might be some conflicts).

**Comment by FrozenPigs** [comment]
This branch has been rebased te master, so it should be good for merging again.

**Comment by Ambrevar** [comment]
Thanks, I'll look into it as soon as possible.

**Comment by Ambrevar** [comment]
Merged, thanks!

**Pull request closed without merging**
