### PR TITLE
Wip multiselection

### PR DESCRIPTION
**Pull request by Ambrevar**
I had to base this on the "functional config" pull request as well, so this pull request only includes the commits from today, the 27th (starts at 
fcd8343).

By the way: this is *awesome*!!!

### CODE REVIEW

**Comment by jmercouris** [comment]
This is... a big pull request :D

**Comment by Ambrevar** [comment]
Not that big if you narrow it down to today's commits!

**Comment by vindarel** [comment]
I can build it and not start it:

```
<INFO> [17:41:11] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.21356
 <WARN> [17:41:11] next remote.lisp (current-buffer) - No active window.
 <WARN> [17:41:11] next minibuffer.lisp (%echo-status) -
  Can't echo 'MINIBUFFER-MODE enabled.' without status buffer or interface
WARNING:
   Method handler (NEXT::CORE-OBJECT
                   NEXT::WINDOW-WILL-CLOSE) signaled an error: There is no applicable method for the generic function
                                                                 #<STANDARD-GENERIC-FUNCTION HOOKS:OBJECT-HOOK (1)>
                                                               when called with arguments
                                                                 (NIL
                                                                  NEXT:WINDOW-DELETE-HOOK).
See also:
  The ANSI Standard, Section 7.6.6.
<ERROR> [17:41:12] next remote.lisp (%rpc-send fun3) -
  RPC connection failed: Method error: "Message recipient disconnected from message bus without replying".
<ERROR> [17:41:12] next remote.lisp (%rpc-send fun3) -
  RPC connection failed: Method error: "The name engineer.atlas.next.platform was not provided by any .service files".
<ERROR> [17:41:12] next remote.lisp (%rpc-send fun3) -
  RPC connection failed: Method error: "The name engineer.atlas.next.platform was not provided by any .service files".
<ERROR> [17:41:12] next remote.lisp (%rpc-send fun3) -
  RPC connection failed: Method error: "The name engineer.atlas.next.platform was not provided by any .service files".
<ERROR> [17:41:12] next remote.lisp (%rpc-send fun3) -
  RPC connection failed: Method error: "The name engineer.atlas.next.platform was not provided by any .service files".
<ERROR> [17:41:12] next remote.lisp (%rpc-send fun3) -
  RPC connection failed: Method error: "The name engineer.atlas.next.platform was not provided by any .service files".
<ERROR> [17:41:12] next remote.lisp (%rpc-send fun3) -
  RPC connection failed: Method error: "The name engineer.atlas.next.platform was not provided by any .service files".
Unhandled SB-PCL::INITARG-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                             {10007285B3}>:
  Invalid initialization argument:
    :NAME
  in call for class #<STANDARD-CLASS NEXT:HELP-MODE>.
See also:
  The ANSI Standard, Section 7.1.2

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10007285B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-PCL::INITARG-ERROR {10076DA913}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-PCL::INITARG-ERROR {10076DA913}>)
2: (INVOKE-DEBUGGER #<SB-PCL::INITARG-ERROR {10076DA913}>)
3: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<SB-PCL::INITARG-ERROR {10076DA913}>)
4: (SB-KERNEL::%SIGNAL #<SB-PCL::INITARG-ERROR {10076DA913}>)
5: (ERROR SB-PCL::INITARG-ERROR :CLASS #<STANDARD-CLASS NEXT:HELP-MODE> :INITARGS (:NAME))
6: (SB-PCL::INITARG-ERROR #<STANDARD-CLASS NEXT:HELP-MODE> (:NAME))
7: ((:METHOD MAKE-INSTANCE (CLASS)) #<STANDARD-CLASS NEXT:HELP-MODE> :NAME "HELP-MODE" :BUFFER #<NEXT:BUFFER {1006FF3E13}> :BUFFER #<NEXT:BUFFER {1006FF3E13}> :ACTIVATE T) [fast-method]
8: (NEXT:HELP-MODE :BUFFER #<NEXT:BUFFER {1006FF3E13}> :ACTIVATE T)
9: ((:METHOD NEXT::INITIALIZE-MODES (NEXT:BUFFER)) #<NEXT:BUFFER {1006FF3E13}>) [fast-method]
10: (NEXT:RPC-BUFFER-MAKE :TITLE "*Help*" :DEFAULT-MODES (NEXT:HELP-MODE NEXT::WEB-MODE NEXT:ROOT-MODE) :DEAD-BUFFER NIL)
11: (NEXT:MAKE-BUFFER :TITLE "*Help*" :MODES (NEXT:HELP-MODE NEXT::WEB-MODE NEXT:ROOT-MODE))
12: (NEXT:HELP)
13: (NEXT::DEFAULT-STARTUP NIL)
14: (NEXT:ENTRY-POINT)
15: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
16: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<CLOSURE (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {10055282EB}>)
```

**Comment by Ambrevar** [comment]
You might have to update / delete your init file.
Note that now you can run it with `-i ""` to bypass the init file.

This is a bad error message nonetheless, I'll see if I can fix it.

**Comment by Ambrevar** [comment]
Actually that's not the problem: the backtrace shows that .fasls were
mixed up.  Clean the fasls and rebuild, it should work.

**Comment by vindarel** [comment]
Works beautifully.

Hard request: switch keybindings C-r and C-R. C-r sould reload the current buffer without a prompt.

We should have two commands: reopen previous buffer, no prompt, and reopen buffers, with multiselection.

We'll have to add options and think on usage to get buffers ordering right. When I reopen one or many buffer, I want to go to it. No?

**Comment by vindarel** [comment]
Same with `C-b`: it had no prompt before. We should have two commands. But that's unrelated to this PR, feel free to ignore.

**Comment by Ambrevar** [comment]
- C-r: I did this on purpose because the incentive was that we don't
  want the users to reload "by accident", potentially losing the state of
  the page (e.g. text fields).  C-R is harder to press, thus acts as a
  confirmation (like shift-delete on some file managers).

- C-b/C-f: You can go back/forward without minibuffer query with
  button8/button9.
  I thought that C-b/C-f are more suited to a minibuffer query since if
  you press them, it means your hands are already on the keyboards.
  It's important the history-backwards-query / history-forwards-query
  are _very_ accessible: considering how kick-ass they are, I want to
  use it all the time!

- reopen: we already have 2 commands, although they are not consistently
  named, because the other one is `undo-buffer-deletion`.  I propose we
  rename it.

> We'll have to add options and think on usage to get buffers ordering right. When I reopen
> one or many buffer, I want to go to it. No? 

Forgot that indeed.  I'm thinking we should focus on the first or the
last one that was selected.

**Comment by Ambrevar** [comment]
Merged with 5785bf498fc01edb168922721030ec22b8f062a5.

**Comment by Ambrevar** [comment]
For the question of "which buffer to focus", see #417 as well.

**Comment by vindarel** [comment]
> - C-r: I did this on purpose because the incentive was that we don't want the users to reload "by accident", potentially losing the state of the page (e.g. text fields). C-R is harder to press, thus acts as a confirmation (like shift-delete on some file managers).

I don't buy that. Our users are power users. All other vim-ish extensions use simply "r". C-r is already hard to press by accident. The website or the browser are responsible for keeping the state. Semantics: C-r does one thing, C-R (more keypressses) is supposed to do more.

> considering how kick-ass they are, I want to use it all the time!

they are kick-ass but here I think: "oh damn, a developer doing UX" ;)

C-b: again need of being smarter, if there is a single page back, don't ask.

Maybe C-b should not ask, but C-f should.

>  I thought that C-b/C-f are more suited to a minibuffer query since if you press them, it means your hands are already on the keyboards.

They are on the keyboard, I want to go fast, I don't want always a prompt…

**Comment by Ambrevar** [comment]
Actually I've changed my mind: when the users wants to _chain_ commands,
it needs to be easy.

C-b C-b C-b

is easier than

C-B C-B C-B

Let's swap the bindings then.

**Pull request closed without merging**
