### PR TITLE
Don't be a Frankendebian!

### PR DESCRIPTION
**Pull request by equwal**
Address https://github.com/atlas-engineer/next/issues/171

### CODE REVIEW

**Comment by jmercouris** [comment]
I'm going to close this issue, since you have conveniently opened another one already.

**Comment by jgkamat** [comment]
John Mercouris writes:

> I'm going to close this issue, since you have conveniently opened another one already.

This is a PR, the other one is an issue

**Comment by jmercouris** [comment]
I'm sorry, I didn't realize that, I am very tired, my apologies!

**Comment by jmercouris** [comment]
Reading through this, I would rather not put a bunch of footnotes within the main readme about installing from source on Debian. I think probably we'll edit the readme entirely for the front and add all of this information the developer readme.

**Comment by equwal** [comment]
Feel free to close this if you decide not to use the edits.

**Comment by Ambrevar** [comment]
@jmercouris : This is such a common issue that we should make it as visible as possible I think.
I'll merge this, we can move it later if you think it'd be more relevant that way.

**Comment by Ambrevar** [comment]
@equwal : Thanks!

**Pull request merged**
