### PR TITLE
Add space to cursor-forwards-word and cursor-backwards-word

### PR DESCRIPTION
**Pull request by FrozenPigs**
This seems like something that should have already been there, but if not feel free to say why space was not included in the `cursor-backwards-word` and `cursor-forwards-word` functions. Also a little question, do you happen to have an IRC you guys hang out on?

### CODE REVIEW

**Comment by jmercouris** [comment]
No reason really, at the time I was thinking about URLs, and URLs don't have spaces in them, however you can interact with more than just URLs in the minibuffer, so that does make sense

on IRC Freenode you can find us on #next-browser

**Comment by jmercouris** [comment]
Ok, so I ran this patch a little bit, and I realized that `GENERATE-INPUT-HTML` has to be modified to accommodate this change as consecutive spaces in Webkit are breaking. I tried to simply do a string substitution on the `input-buffer` for spaces with `&nbsp`, however that was simply emitted over and over again into the mini buffer when typing. So, the change is good, but some other changes are necessary to properly accommodate it.

**Comment by FrozenPigs** [comment]
What exactly is the issue with consecutive spaces? If there is any extra chanages you need from this pull request feel free to ask, though my common lisp knowledge is fairly limited. I am also around in the IRC if you need to talk.

**Comment by Ambrevar** [comment]
@jmercouris I'm not sure I understand the problem either.
@FrozenPigs : there has been some recent changes on those very functions, can you rebase your pull request on master?  Thanks!

**Comment by FrozenPigs** [comment]
@Ambrevar Was that what I did to that branch right? I'm not the best at all this git stuff just yet heh. And that problem he was talking about is when you enter space in the minibuffer multiple times, only one appears. I belive he said that it was already an issue before this commit.

**Comment by Ambrevar** [comment]
Thanks, I'll look into this as soon as possible.

**Comment by Ambrevar** [comment]
Merged, thanks for your contribution!
I'll work on @jmercouris point with the inability of inserting multiple spaces.

**Pull request closed without merging**
