### PR TITLE
Composed request resource

### PR DESCRIPTION
**Pull request by Ambrevar**
See the commit messages.

After this gets merged:

- Shall we rename the lengthy `request-resource-hook` to `request-hook`?
- `set-url-hook` seems to be completely superseded by `request-hook`.  I suggest removing it for now because it's not very useful and might confuse users as in #517.  Or at least unexport it for now and if it ever gets requested by some users we can reenable it later.  It's easier in this direction because we can't remove / unexport after 2.0 (it would be API-breaking).

### CODE REVIEW

**Comment by jmercouris** [comment]
Unexport is sufficient I believe. I still think it has a use case :-)
I would not rename request-resource-hook because the name is perfectly descriptive, request-hook is ambiguous

**Comment by jmercouris** [comment]
I'll take a look at this on Monday

**Comment by Ambrevar** [comment]
A "request" is descriptive enough I think.
A user might wonder "what is a resource?"

**Comment by Ambrevar** [comment]
In case the consequences of this change were not clear: now we can hi-jack the URLs of any link that is clicked, downloaded, requested otherwise.  And we can _compose_ those hi-jacks.

For instance, an "old-reddit" handler may change "www.reddit.com" to "old.reddit.com".
And another handler may decide to switch to the mobile version.  Both handlers can work together (and be toggled at will) without having to be _aware_ of each other.

**Comment by jmercouris** [comment]
How is the order of the execution decided?

**Comment by jmercouris** [comment]
In other words, how can hooks that compose chain together in such a way that they all process the data as expected?

Would some orders not be invalid? Could we leverage an expert system to automatically deduce the order in which the hooks should execute?

**Comment by jmercouris** [comment]
OR is it that every hook can work with ANY type of data in ANY order?

**Comment by Ambrevar** [comment]
The hooks library offers a very nice features: hooks have a `:combination` slot that specifies how the handlers are executed.
`hooks` offers these by default:
- default-combine-hook (emacs style)
- combine-hook-until-failure
- combine-hook-until-success
- combine-composed-hook

For our needs in resource-request-hook, I've added `combine-composed-hook-until-non-nil-second-value` which composes all the handlers from head to tail until one returns a non-nil second value.

Does that make sense?

**Comment by Ambrevar** [comment]
Practically, this means that if we enable a mode that adds a handler to the hook, it gets executed before the existing handlers.  In practice, I think this is what we want.

Note that a mode is free to place the the handler wherever they want in the hook.  For instance, if A needs to be after B if present, we can always search for B and add A there; or, if B is missing, add A at the beginning.

As you said, we can derive a system for sorting the handlers if the need ever arises.  I think it's an orthogonal issue that we can work on later.  Thoughts?

**Comment by jmercouris** [comment]
That sounds just fine to me, I didn't realize that logic was already in the hooks library, I guess I did not study it well enough! As per the expert system, you are absolutely correct, that is another issue for another time :-)

Anyways, looks ready to me! Nice work!

**Comment by Ambrevar** [comment]
OK, I'll merge soon.
What about renaming the hook, in the end?

**Comment by jmercouris** [comment]
I don't feel too strongly about it, I am OK with it in any case. My opinion is still that we are requesting a resource, and not for example a remote execution call...I also like that the nomenclature is consistent with the web renderer when using "request resource"

**Comment by Ambrevar** [comment]
Merged in 4a8b0e890a38fdebe1cd5a6f7a6f3032955e6487.

**Pull request closed without merging**
