### PR TITLE
Bind keys to function symbols instead of functions.

### LINKED ISSUE #575: define-command does not redefine + creates doubles in M-x
From the REPL, evaluating a  new definition of a `define-command` does not change the command of the running instance.

Besides, it's possible to create duplicate entries in M-x while it should not be.

### PR DESCRIPTION
**Pull request by Ambrevar**
Now calling a redefined function from a binding works.

Fixes #575.

### CODE REVIEW

**Comment by jmercouris** [comment]
Yay!

**Comment by Ambrevar** [comment]
OK to merge?

**Comment by jmercouris** [comment]
Yes, looks ready to me!

do the forms: `(:code (binding-keys #'search-buffer))` need to be changed?

**Comment by jmercouris** [comment]
I would imagine that they do... just checking though :-) I see no other issues

**Comment by Ambrevar** [comment]
Yes they do, thanks for catching this!

**Comment by Ambrevar** [comment]
Merged with 92a2905cfed39b0f9a0d0967f444a234d89e5658.

**Pull request closed without merging**
