### PR TITLE
Fix hint box overlapping

### PR DESCRIPTION
**Pull request by alexherbo2**

### CODE REVIEW

**Comment by Ambrevar** [comment]
Overlapping with what?  :p

**Comment by jmercouris** [comment]
Probably each other?

**Comment by alexherbo2** [comment]
The site elements.  It happens the site elements get a higher priority in the overlapping stack.  [`z-index`] ensures hint boxes are always on-top.

[`z-index`]: https://developer.mozilla.org/en-US/docs/Web/CSS/z-index

**Comment by Ambrevar** [comment]
OK, sounds good.  Do you have an example website so we can test it?

According to https://developer.mozilla.org/en-US/docs/Web/CSS/integer#Syntax, integers have no standard range.  What would be the most reasonable value then?

Either way, we should probably comment the magic number :)

**Comment by alexherbo2** [comment]
The maximum: 2147483647 (2³¹ − 1)

You can see here with the GitHub Star button.

**Comment by Ambrevar** [comment]
Indeed, this fixes the GitHub buttons, thanks!

I understand the maximum you chose is over 32 signed integers, but the Mozilla documents I've linked explicitly states that this is not standard.

Should we stick to this value, I prefer `(1- (expt 2 31))`, it helps clarifying the meaning of the value.

**Comment by Ambrevar** [comment]
I'll merge and add a link to the Mozilla pages, explaining that the range might have to be tweaked depending on the web renderer.

**Comment by Ambrevar** [comment]
Thanks!

**Pull request merged**
