### PR TITLE
fixes, webkit and gtk 

### PR DESCRIPTION
**Pull request by vindarel**
given https://github.com/atlas-engineer/next/issues/127, hope that's relevant.

this builds with my setup.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Commit 82d9e3f9b4edd0bc458af20be5c76369ae96d5ef breaks Next on my system.  It builds, but then starting it yields a

``` lisp
Unhandled SQLITE:SQLITE-CONSTRAINT-ERROR in thread #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING
                                                      {10045A5EB3}>:
  Error while stepping an sqlite statement.
Code CONSTRAINT: NOT NULL constraint failed: history.url.
Database: /home/ambrevar/.local/share/next/history.db
SQL: insert into history (url) values (?)

Backtrace for: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10045A5EB3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SQLITE:SQLITE-CONSTRAINT-ERROR "Error while stepping an sqlite statement." {10054AA2F3}> #<unused argument> :QUIT NIL)
1: ((LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) #<SQLITE:SQLITE-CONSTRAINT-ERROR "Error while stepping an sqlite statement." {10054AA2F3}> #<FUNCTION (LAMBDA (SB-THREAD::C SB-THREAD::H) :IN SB-THREAD::%EXIT-OTHER-THREADS) {21CA73AB}>)
2: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SQLITE:SQLITE-CONSTRAINT-ERROR "Error while stepping an sqlite statement." {10054AA2F3}>)
3: (INVOKE-DEBUGGER #<SQLITE:SQLITE-CONSTRAINT-ERROR "Error while stepping an sqlite statement." {10054AA2F3}>)
4: (ERROR SQLITE:SQLITE-CONSTRAINT-ERROR :FORMAT-CONTROL "Error while stepping an sqlite statement." :FORMAT-ARGUMENTS NIL :DB-HANDLE #<SQLITE:SQLITE-HANDLE {10054A9263}> :ERROR-CODE :CONSTRAINT :ERROR-MSG "NOT NULL constraint failed: history.url" :STATEMENT #<SQLITE:SQLITE-STATEMENT {10054A9E83}> :SQL "insert into history (url) values (?)")
5: (SQLITE:SQLITE-ERROR :CONSTRAINT "Error while stepping an sqlite statement." :STATEMENT #<SQLITE:SQLITE-STATEMENT {10054A9E83}> :DB-HANDLE NIL :SQL-TEXT NIL)
6: (SQLITE:STEP-STATEMENT #<SQLITE:SQLITE-STATEMENT {10054A9E83}>)
7: (SQLITE:EXECUTE-NON-QUERY #<SQLITE:SQLITE-HANDLE {10054A9263}> "insert into history (url) values (?)" NIL)
8: (SQLITE:EXECUTE-NON-QUERY #<SQLITE:SQLITE-HANDLE {10054A9263}> "insert into history (url) values (?)" NIL) [more]
9: (NEXT::HISTORY-ADD NIL)
10: (NEXT::ADD-OR-TRAVERSE-HISTORY #<NEXT::DOCUMENT-MODE {1004F5B613}>)
11: (GOBJECT::CALL-WITH-RESTARTS #<CLOSURE (LAMBDA (INTERFACE::WEBVIEW INTERFACE::LOAD-EVENT) :IN INTERFACE:WEB-VIEW-SET-URL-LOADED-CALLBACK) {1005069E7B}> (#<CL-WEBKIT2:WEBKIT-WEB-VIEW {1005066E33}> :WEBKIT-LOAD-STARTED))
12: ((LAMBDA (GOBJECT::CLOSURE GOBJECT::RETURN-VALUE GOBJECT::COUNT-OF-ARGS GOBJECT::ARGS GOBJECT::INVOCATION-HINT GOBJECT::MARSHAL-DATA) :IN "/home/ambrevar/quicklisp/dists/quicklisp/software/cl-cffi-gtk-20160208-git/gobject/gobject.signals.lisp") #.(SB-SYS:INT-SAP #X7FFFDC1385A0) #.(SB-SYS:INT-SAP #X00000000) 2 #.(SB-SYS:INT-SAP #X7FFFE0B5DE40) #<unused argument> #<unused argument>)
13: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/home/ambrevar/quicklisp/dists/quicklisp/software/cl-cffi-gtk-20160208-git/gobject/gobject.signals.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
14: ("foreign function: funcall_alien_callback")
15: ("foreign function: callback_wrapper_trampoline")
16: ("foreign function: #x201004DB")
17: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
18: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
19: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
20: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
21: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
22: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
23: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFE0B5ED5B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10045A5EB3}>> NIL T NIL)
24: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10045A5EB3}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {10045A5E5B}> NIL)
25: ("foreign function: call_into_lisp")
26: ("foreign function: new_thread_trampoline")

unhandled condition in --disable-debugger mode, quitting
```

Any clue what's happening?

If I revert the commit, everything is find.  I cannot reproduce @vindarel's issue.  @vindarel, could you double check?
Can you list the installed libraries in `~/common-lisp` and `quicklisp/local-projects`?
Also make sure the SBCL cache is clean (remove everything in `~/.cache/common-lisp` if you are unsure).

**Comment by vindarel** [comment]
Damn. This looks exactly like https://github.com/atlas-engineer/next/pull/130

**Comment by jmercouris** [comment]
My thoughts are that likely you both have different versions of cl-cffi-gtk. Since the commit worked on my machine and @Ambrevar's machine, but only had problems on @vindarel's machine, the most logical conclusion is that there is something wrong with @vindarel's installation or set-up of `cl-cffi-gtk` and we probably should revert the commit. 

All of this said, I don't have the bandwidth to test on Linux or spin up a new VM and try it for myself, so @Ambrevar please use your judgement.

**Comment by Ambrevar** [comment]
The offending commit also crashes on Arch Linux for me, so I've reverted it for now.  @vindarel: Please report if you are still experiencing issues.

**Comment by vindarel** [comment]
+1 suits me fine.

**Pull request merged**
