### PR TITLE
port.lisp: lookup for two possible executables

### PR DESCRIPTION
**Pull request by vindarel**
look for either "next-gtk-webkit" or "next-pyqt-webengine" in the
current directory, ports/, or return "name".

we can now run ./next inside our pyqt dist/ directory.

It works©, but a review is welcome and this might render obsolete some code, such as `ports/gtk-webkit.lisp`.

### CODE REVIEW

**Comment by alexanderbarbosa** [comment]
at last.

That means, users wont need to set executyable port path?! if so, great!

**Comment by alexanderbarbosa** [comment]
It correctly find ports executable, if Next is installed as global package.

It fails on Local builds.

I reckon, that is exactly how it should be!

**Comment by jmercouris** [comment]
You're correct about it rendering `ports/gtk-webkit.lisp` obsolete, that was one of the ideas we'd discussed. The idea being that, nothing should be port specific within the Lisp code. All of those details should be handled by the platform port.

The second thing that we talked about was actually just renaming the executable to output as next-platform on both GTK and PyQtWebEngine so that we don't have any confusion. Few people will run both binaries simultaneously, and if they want to, they can always customize the Lisp core to allow for this.

**Comment by vindarel** [comment]
> It correctly find ports executable, if Next is installed as global package.

thanks for testing.

> It fails on Local builds.

@alexanderbarbosa What do you actually mean by this ? For me it works when I run `./next` at the project root or on `ports/gtk-webkit` (if there is a `next-gtk-webkit` binary).

> The second thing that we talked about was actually just renaming the executable to output as next-platform on both GTK and PyQtWebEngine so that we don't have any confusion. Few people will run both binaries simultaneously,

That is actually a solution too. I'd go by keeping how it is now for the few of us that run both.

**Comment by alexanderbarbosa** [comment]
@vindarel 

Cant say why, but symlink next binary to a $PATH folder it dont behave as if executing in project root folder.

**Comment by jmercouris** [comment]
This branch has been covered by the merging of pyqt-webengine.

**Pull request closed without merging**
