### PR TITLE
Add iolib to the inputs in guix.scm

### PR DESCRIPTION
**Pull request by khinsen**

### CODE REVIEW

**Comment by gravitational-dark-light** [comment]
Thank you, I have spent the day trying to get next running with the latest commit, but I don't know enough of guile scheme yet, so I only managed the first line...

**Comment by Ambrevar** [comment]
Thank you!
We shouldn't need the iolib subpackages, something needs fixing in Guix.  I'll check it out.

**Comment by Ambrevar** [comment]
Good news, I've fixed iolib in upstream Guix.
Now we only need to depend on iolib.

**Comment by gravitational-dark-light** [comment]
> Good news, I've fixed iolib in upstream Guix. Now we only need to depend on iolib.

Now sbcl asks for iolib-multiplex, the PR included it, and worked fine, Perhaps guix needs some more fixing?

**Comment by gravitational-dark-light** [comment]
> > Good news, I've fixed iolib in upstream Guix. Now we only need to depend on iolib.
> 
> Now sbcl asks for iolib-multiplex, the PR included it, and worked fine. Perhaps guix needs some more fixing?

Never mind, I forgot to upgrade guix

**Comment by khinsen** [comment]
Great, thanks @Ambrevar for cleaning this up in Guix, it didn't look nice!

**Pull request merged**
