### PR TITLE
Use single history database table so that clicked-on links also appea…

### PR DESCRIPTION
**Pull request by Ambrevar**
…r in minibuffer.

### CODE REVIEW

**Comment by vindarel** [comment]
\+1 LGTM

**Comment by jmercouris** [comment]
There is not the data here differentiating from inputted URLs and typed URLs, do we not want to do that via a column?

**Comment by Ambrevar** [comment]
In practice I find the current behaviour to be very usable.  If we are going to drop SQlite and use a "how it was added" slot, then I'd rather do that straight away.  (After 1.3.)

**Comment by jmercouris** [comment]
OK, then!

**Pull request merged**
