### PR TITLE
add check for textarea tag when determining vi-insert-mode

### PR DESCRIPTION
**Pull request by 4t0m**
I think this addresses #384.  It was only checking for input tags and not textarea tags.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Thanks for digging this out, it seems to work indeed! :)
(Had been annoying me for way too long :p)

Just a nit: can you rename the function to `input-tag-p` and can you make the defmethod a function, and use type declaration to enforce type checking:
```
(declaim (ftype (function (string)) input-tag-p))
(defun input-tag-p (tag)
  (or (string= tag "INPUT")
      (string= tag "TEXTAREA")))
```

Methods should only be used if we are actually going to dispatch methods (e.g. other objects would have an "input-tag-p" method).  Methods should not be used for type checking.

**Comment by Ambrevar** [comment]
To clarify: in Common Lisp, booleans and boolean-returning function are conventionally suffixed with `-p`, which stands for "predicate".
Then you don't need "is-".

**Comment by 4t0m** [comment]
Should be fixed!  Thanks for the pointer about conventions :).  It's all stuff I want to learn/understand.

**Comment by Ambrevar** [comment]
You're welcome, and thanks for this very useful fix!

**Pull request merged**
