### PR TITLE
Wip mode package hooks and more

### PR DESCRIPTION
**Pull request by Ambrevar**
Get ready for the biggy! :)

This needs a bit of testing, but it's mostly working at the moment.

Question:
- Should we move minibuffer-mode and help-mode to separate packages?  I'd think so.

Next steps:
- Update tests and doc.
- Add hooks!

### CODE REVIEW

**Comment by Ambrevar** [comment]
I've added hook support!  In terms of code, it's really not hard (I've leveraged cl-hooks).
In terms of design, it raises tons of questions:

- Where do we add hooks?  Before or after of both?

- I feel like tons of hooks are missing, in particular around networking, but I'm still fumbling here.  Time will tell I suppose.

- I'd like to type the hooks so that only functions with the right signature are accepted.

- I realized that it would be beneficial to control _how_ handlers are executed, that is to say, should they be `#'mapcar` ed over  the arguments, or `#'compose` d, etc.?  For instance, the `set-url` hook should certainly chain the handlers over the successive results of the change made to the URLs, otherwise it makes no sense.  For now I've implemented a hacky `run-composed-hook`, but I'd like to give more control to the user so they can configure the hook on how to execute the handlers.
I've reported this issue upstrea: https://github.com/scymtym/architecture.hooks/issues/2.

**Comment by Ambrevar** [comment]
If you want to test, you can try this cute hook which force-switches the URL to old.reddit.com:

```lisp
(defun old-reddit-hook (url)
  (let* ((uri (quri:uri url)))
    (if (search "www.reddit" (quri:uri-host uri))
        (progn
          (setf (quri:uri-host uri) "old.reddit.com")
          (let ((new-url (quri:render-uri uri)))
            (log:info "Switching to old Reddit: ~a" new-url)
            new-url))
        url)))
(add-to-default-list #'old-reddit-hook 'buffer 'load-hook)
```

You can add it to ~/.config/next/init.lisp.

**Comment by Ambrevar** [comment]
Other hook question: wouldn't it be nice to be able to list _all the hooks_?
But I'm not sure how to proceed.  With `cl-hooks` hooks don't really have a type, they are just list.  But cl-hooks stores some stuff internally, so maybe we can look there.

**Comment by Ambrevar** [comment]
About the hook handler composition: it seems that it's a novel idea, Emacs does not support it and I don't think that Lem or Nomad do either.  Maybe an idea worth sharing!

**Comment by vindarel** [comment]
LGTM, but needs tests and a minimal doc. I can write a little tutorial afterwards.

Also, let's merge my PR first :D

**Comment by vindarel** [comment]
oh, and it's awesome :) (hooks could have been made in another PR, no?)

**Comment by Ambrevar** [comment]
For doc and tests, I left them out on purpose until someone (you :p) reviewed it.

For future "big" efforts, I believe this is a more efficiant workflow: should the patch set be rejected (or modified significantly), the effort put in documentating and testing would go to waste.

I'll add doc and tests as soon as possible.

For the PR: I needed hooks to be based off the same branch, but I could have created another PR indeed, my bad! :p

**Comment by Ambrevar** [comment]
What do you think of the following TODO:
```
   ;; TODO: Rename `load-hook' to `set-url-hook'?
```

**Comment by Ambrevar** [comment]
There could be 2 hooks: one that is run whenever the buffer displays something, e.g. a REPL is refreshed; the other one could be set whenever we "set the URL", that is to say, we query the load of a network resource.

**Comment by Ambrevar** [comment]
I've updated the docstrings and the manual.

**Comment by Ambrevar** [comment]
Merged.

**Comment by Ambrevar** [comment]
Commit f6ffa60a67d8221fe93e20a2bd137435d846af38.

**Comment by Ambrevar** [comment]
@vindarel: You mentioned tests but I'm not sure what to test here.
The separate package mostly have to do with compilation, so the test here is "does it compile or not"?
For hooks, I believe the cl-hooks library upstream should to the tests.

Thoughts?

**Pull request closed without merging**
