### PR TITLE
assets/next.desktop: Init

### PR DESCRIPTION
**Pull request by Ambrevar**
Before merging this, we need to settle on a few points:

- Name: See issue #133 .
- Icon names: Should we rename them to `next_*`?
- Exec: See issue #133 as well.
- Actions: What do we support now?

### CODE REVIEW

**Comment by jmercouris** [comment]
Hi Pierre, I've replied to the questions in the other issues, interested in your thoughts as well,

-John

**Comment by Ambrevar** [comment]
> What do we support now? Currently we only support MacOS, our subsequent release we will > support Linux & MacOS

Sorry for the confusion, that's not what I meant.  From the .desktop file:

```
Actions=NewWindow;NewPrivateWindow;
```

**Comment by jmercouris** [comment]
With regards to the desktop file, we have not yet implemented a private window mode, so I would just leave it as "NewWindow"

**Comment by Ambrevar** [comment]
What about the icons?  On GNU/Linux, they should have a unique name or else it will confuse the XDG specifications.

**Comment by jmercouris** [comment]
I guess then, make them whatever the XDG spec says, "next-browser" in this case?

**Comment by Ambrevar** [comment]
I thought you did not want to use "next-browser" but "next" instead?

**Comment by Ambrevar** [comment]
OK, I've corrected the file and merged.

**Pull request closed without merging**
