### PR TITLE
Loading status

### PR DESCRIPTION
**Pull request by Ambrevar**

### CODE REVIEW

**Comment by Ambrevar** [comment]
This expands on the fix for #672.

**Comment by Ambrevar** [comment]
We still have to report network errors properly (i.e. with the :load-failed signal) before closing #672.

**Comment by jmercouris** [comment]
I think (Loading) is too subtle, but that's OK for now

I was goign to add a little CSS loading circle, but decided against it, we can think about it later. Thanks for the fixes!

**Comment by Ambrevar** [comment]
> I was goign to add a little CSS loading circle, but decided against it, we can think about it later. Thanks for the fixes!

Agreed, the loading circle would be nicer, but hey, we worry about
cosmetic after usability :)

**Comment by jmercouris** [comment]
I also decided against the loading circle because I thought it would be distracting, maybe it would be enough to just write "Loading" in bold text or something, anyways we'll see!

**Pull request merged**
