### PR TITLE
Redesigned branding and icon set

### PR DESCRIPTION
**Pull request by neauoire**
I love using Next, and I figured maybe it could do with a bit of a revamp.
This is the icon I use on my fork, I thought maybe other would like it too.

screen shot 2018-10-06 at 9 40 22 am

### CODE REVIEW

**Comment by neauoire** [comment]
The Type is an edited version of`Gotham Book`, at about ~500 weight so it looks good even when small. The padded versions follow the same size as other OS X icons(such as Ableton, etc..) It is meant to look a bit less childish, and a bit more modern. There is also a white icon version included.

screen shot 2018-10-06 at 9 45 02 am

**Comment by jmercouris** [comment]
Hi, thank you for the kind words, and thank you for the new icon design. I find it very beautiful. My only hang-ups are that previous versions of the Next icon looked similar, and everyone kept pointing to the similarity between it and the Next logo for the now defunct software company https://en.wikipedia.org/wiki/NeXT.

I'll have to think about it, or maybe we can put it up to a community vote or something, not sure. Please give me some time, and I will get back to you.

**Comment by neauoire** [comment]
next

Well, I do have this other thing. It has no color tho.

**Comment by neauoire** [comment]
screen shot 2018-10-07 at 6 55 26 am

**Comment by jmercouris** [comment]
Yes, I saw and followed your voyage! Glad to see you made it out of fiji and past those small islands, I assume you’re in Japan again?

**Comment by neauoire** [comment]
Ah! Thanks for keeping us with our adventure! We're in [Majuro, Marshall Islands](https://www.patreon.com/posts/from-fiji-to-22735188).

I've updated the PR :)

**Comment by jmercouris** [comment]
Looks really great, thank you so much for the PR!

**Comment by jmercouris** [comment]
Also, I'll try to spread the word about your Patreon a little bit, maybe we can put it in some credits somewhere, I'll think about how to do it

**Comment by neauoire** [comment]
Thank you so much, keep up the good work with Next.
I'm eagerly pulling all new changes. I'm glad I could help a bit :)

**Pull request merged**
