### PR TITLE
CLOS-style configuration

### LINKED ISSUE #419: Functional config & hooks
A discussion on the general idea of _configurability_: This is an iteration on
the question of hooks (https://github.com/atlas-engineer/next/issues/383) and
the controversial topic of functional configuration
(https://github.com/atlas-engineer/next/pull/397).

--------------------------------------------------------------------------------

I just had an epiphany when working with the set-url hook:
the handlers take the URL as argument, but not the buffer.  So how do the
handler know which buffer they apply to.  Calling `(current-buffer)` is wrong:
for instance, when we call `reload-buffer` over multiple buffers,
`(current-buffer)` always returns the same buffer, not the buffer being
reloaded.

Possible fixes:

- Add a `buffer` parameter.  But it fits badly with `run-composed-hook` which
  calls the next handler over the return value of the previous.  Even if we pass
  the buffer along, we've got no strong guarantee that no handler is returning a
  different buffer, thus breaking the integrity of the hook.
  Beside, it really feels like we are passing along an information that should
  already be there, because the hook _belongs_ to the buffer.

- Replace the named handler by a closure over the buffer.  This seems right, but
  there is a problem: a closure is anonymous, and hooks don't like lambdas as
  the Emacs experience tells us:

  - Lambdas are not comparable and thus duplicates can't be removed and will
    stack up.

  - They are black boxes to the user, we can't know what they do.

  - It's impractical to remove a lambda interactively since it has no name.

So what if we created a `handler` class with the following slots:

- Name / description, e.g. `handler that sets the search engine to '("foo" "bar")`.
- The function, possibly a lambda.
- `place`: (Optional) If the function is a setter, describe the place being set,
  e.g. `'(remote-interface buffer-make-hook load-hook)`.
- `value`: (Optional) If the function is a setter, describe the value,
  e.g. `'(1 2 3)`.

We would modify `add-to-hook` to either accept functions or `handler`s but not
anonymous functions.
Then `run-hooks` should be able to run both regular functions and
the above `handler`s in a hook.

Handlers should be comparable so that the hooks can remove duplicates.
I can think of various criteria for comparison:

- If function is the same (non-lambda only).
- Or, if place and value are set, if they are `EQUAL`.  This is only useful for
  setters.
- I'm not sure it makes sense to compare the name/description.

--------------------------------------------------------------------------------

In https://github.com/atlas-engineer/next/pull/397, we discussed new
"functional" (stateless) ways to configure Next.
I was suggesting

```lisp
(defun my-minibuffer-defaults (minibuffer)
  (setf
   (minibuffer-line-height minibuffer) "1.1em")

(defun my-interface-defaults ()
  (hooks:add-to-hook (hooks:object-hook *interface* 'minibuffer-make-hook)
                     #'my-minibuffer-defaults))

(hooks:add-to-hook '*after-init-hook* #'my-interface-defaults)
```

Obviously this is not the easiest.

We could use helper macros but they would necessarily add _unnamed_ handlers to
hooks...  Which is not a problem anymore if we use the above `handler` types!

Then we can write macros to set default values (dummy code):

```
(defmacro set-default (object slot value)
  ...
  (cond
   ((eq object 'buffer)
    (add-hook *after-init-hook*
        (make-handler
           :description (format nil "Register handler to set buffer's ~a to ~a" slot value)
           :place '(remote-interface buffer-make-hook)
           :value value
           :function (lambda ()
                      (add-hook buffer
                         (make-handler
                           :description (format nil "Set buffer's ~a to ~a" slot value)
                           :place slot
                           :value value
                           :function (lambda (buffer)
                                       (setf (slot-value buffer slot) value))))))))
   ...))
```

This would allow us to set values this way:

```lisp
(set-default 'buffer 'minibuffer-line-height "1.1em")
```

We could also support
```lisp
(set-default 'buffer
  'minibuffer-line-height "1.1em"
  'minibuffer-font-size "1.0em")
```
to avoid flooding `*after-init-hook*`.

Thoughts?

### PR DESCRIPTION
**Pull request by Ambrevar**
This should mostly fix #419.

Example init.lisp:

```lisp
(defclass my-interface (remote-interface)
  ((download-directory :initform "~/temp")))

(setf *remote-interface-class* 'my-interface)
```

That's it!
Note that we can combine class settings by using multiple inheritance.

### CODE REVIEW

**Comment by Ambrevar** [comment]
As opposed to what I said in #419, we don't have proper type-checking over `*window-class*`, etc.
We could enable it with the following:

```lisp
(defun window-class-symbol-p (class-symbol)
  (closer-mop:subclassp (find-class class-symbol)
                        (find-class 'window)))
(deftype window-type ()
  `(satisfies window-class-symbol-p))
(declaim (type (window-type) *window-class*))
```

But note that SBCL fails to perform compile-time type-checking on non-top-level symbols because of the `satisfies`.

I guess it's not a big deal.  Question is: should I even bother with the deftype then?

**Comment by Ambrevar** [comment]
As mentioned in #489, mode configuration still is a bit cumbersome.  What about generating a `*foo-mode-class*` symbol that evalutes to `'foo-mode` by default?

This way configuring the class defaults would look like this:

```
(defclass my-web-mode (web-mode)
  (keymap-schemes ...))

(setf *web-mode-class* 'my-web-mode)
```

Thoughts?

**Comment by jmercouris** [comment]
I like the idea, but I feel like we could take it one step further using reader macros to possibly automate that whole process for the user... I need to think a little bit about it. As an aside, I am very much liking the CLOS style configuration, I think it is a fantastic idea!

**Comment by Ambrevar** [comment]
Macros or reader-macros?  What do you have in mind?

**Comment by jmercouris** [comment]
I have reader macros in mind, I was thinking of a special syntax for people who are new, something to make things simple for them. On the other hand, maybe that is more suited to a `*customize*` buffer of sorts, and we only need provide an SEXP "API".

**Comment by Ambrevar** [comment]
I have implemented the same configuration approach for modes.

Now mode defaults can be configured by define a subclass and then setting the
default class, e.g.

``` common-lisp
(setf *web-mode-class* 'my-web-mode)
```

**Comment by jmercouris** [comment]
Nice!

**Comment by Ambrevar** [comment]
Merged.
@vindarel: Let me know if there is anything you'd like to revert, no problem.

I'll update the documentation just now.

**Comment by vindarel** [comment]
> should I even bother with the deftype then?

yes if it catches errors when loading the init file.

**Comment by vindarel** [comment]
I tried the example from the doc:

```
(defclass my-remote-interface ()
  ((search-engines :initform
    '(("default"
       "https://duckduckgo.com/?q=~a"
       "https://duckduckgo.com/")
      ("yt"
       "https://www.youtube.com/results?search_query=~a"
       "https://www.youtube.com/")
      ("wiki"
       "https://en.wikipedia.org/w/index.php?search=~a"
       "https://en.wikipedia.org/")))))

(setf *remote-interface-class* 'my-remote-interface)
```

and I get:

```
Error: we could not load the init file because of a type error.:
#<TYPE-ERROR expected-type: (SATISFIES REMOTE-INTERFACE-TYPE-P)
             datum: MY-REMOTE-INTERFACE>
```

on the setf.

btw, if I'm not mistaken the type checks don't check slots types?

```
(defmacro define-class-type (class-sym)
  "Define a type named CLASS-SYM-type.
An object of this type is a subclass of CLASS-SYM."
  (let ((type-pred (intern (str:concat (string class-sym) "-TYPE-P")))
        (type-fun (intern (str:concat (string class-sym) "-TYPE"))))
    `(progn
       (defun ,type-pred (class-symbol)
         (closer-mop:subclassp (find-class class-symbol)
                               (find-class ',class-sym)))
       (deftype ,type-fun ()
         '(satisfies ,type-pred)))))
```

**Comment by vindarel** [comment]
and I confirm for the missing type checks:

```
(defclass my-remote-interface (remote-interface)
  ((search-engines :initform
    '(("default"
       "https://duckduckgo.com/?q=~a"
       "https://duckduckgo.com/")
     ;; wrong:
      (42)))))
```

where search-engines is typed:

```
   (search-engines :accessor search-engines
                   :initform '(("default" "https://duckduckgo.com/?q=~a" "https://duckduckgo.com/")
                               ("wiki" "https://en.wikipedia.org/w/index.php?search=~a" "https://en.wikipedia.org/"))
                   :type alist-of-3tuples-strings
```

```
(setf *remote-interface-class* 'my-remote-interface)
MY-REMOTE-INTERFACE
```

should fail.

**Pull request closed without merging**
