### PR TITLE
Show log4cl logs in *Messages* buffer

### PR DESCRIPTION
**Pull request by ebrasca**

### CODE REVIEW

**Comment by Ambrevar** [comment]
Nice, looks good to me!

**Comment by Ambrevar** [comment]
Actually, wait, we already print the `echo-*` messages in the Messages
buffer.

Maybe your proposal would make more sense if we printed the messages to
a dedicated log buffer.  What do you think?

**Comment by jmercouris** [comment]
I thought we should print them to the same buffer, but have an option or key that you can press to show all logs, or echoed, or just logs.

**Comment by jmercouris** [comment]
@Ambrevar - are you OK with this PR as an incremental step?

**Comment by Ambrevar** [comment]
Sure!

**Comment by jmercouris** [comment]
Alright! Done!

**Pull request merged**
