### PR TITLE
Add KDEConnect integration to Next.

### PR DESCRIPTION
**Pull request by pranavats**
Snippets for sending a url to KDEConnect devices.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Really cool!
Instead of anaphoric macros, I suggest you use trivia's `match` (which Next already bundles).

**Comment by jmercouris** [comment]
Thank you for this!

I'm OK with merging this, this just an example extension, though I do agree with @Ambrevar, would be better to use `match`. If you wish @pranavats I can merge.

**Comment by pranavats** [comment]
@jmercouris @Ambrevar Done! Sorry for these many commits.

**Comment by pranavats** [comment]
@jmercouris Feel free to merge the PR, unless you'd like me to change anything.

**Pull request merged**
